# https://github.com/Koihik/LuaFormatter/blob/master/docs/Style-Config.md
break_after_functioncall_lp: true
break_before_functioncall_rp: true
extra_sep_at_table_end: true
break_after_operator: false
spaces_inside_table_braces: true
align_args: false
align_parameter: false
chop_down_parameter: true
